--------------------------------------------------------
--  File created - pi¹tek-czerwiec-19-2020   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ID_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STUDENT"."ID_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 49 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Sequence KLIENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "STUDENT"."KLIENT_SEQ"  MINVALUE 1 MAXVALUE 99999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOPARTITION ;
--------------------------------------------------------
--  DDL for Table AUTO
--------------------------------------------------------

  CREATE TABLE "STUDENT"."AUTO" 
   (	"ID_AUTA" NUMBER, 
	"NAZWA" VARCHAR2(32 BYTE), 
	"ROK" NUMBER, 
	"PRZEBIEG" VARCHAR2(32 BYTE), 
	"POJEMNOSC" VARCHAR2(32 BYTE), 
	"MOC" VARCHAR2(32 BYTE), 
	"CENA" NUMBER, 
	"ID_DEALERA" NUMBER, 
	"ID_SKLEPU" NUMBER, 
	"IMG_AUTO" VARCHAR2(32 BYTE), 
	"HIDDENN" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table DEALER
--------------------------------------------------------

  CREATE TABLE "STUDENT"."DEALER" 
   (	"ID_DEALERA" NUMBER, 
	"NAZWA_DEALERA" VARCHAR2(32 BYTE), 
	"KRAJ_POCHODZENIA" VARCHAR2(32 BYTE), 
	"OPIS_DEALERA" VARCHAR2(500 BYTE), 
	"IMG_DEALER" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table HISTORY
--------------------------------------------------------

  CREATE TABLE "STUDENT"."HISTORY" 
   (	"ID_ZAKUPU" NUMBER, 
	"ID_AUTA" NUMBER, 
	"ID_KLIENTA" NUMBER, 
	"DATA_ZAKUPU" DATE, 
	"NAZWA_CAR" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table KLIENT
--------------------------------------------------------

  CREATE TABLE "STUDENT"."KLIENT" 
   (	"ID_KLIENTA" NUMBER, 
	"IMIE" VARCHAR2(32 BYTE), 
	"TELEFON_KLIENTA" VARCHAR2(32 BYTE), 
	"EMAIL_KLIENTA" VARCHAR2(32 BYTE), 
	"HASLO" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Table SKLEP
--------------------------------------------------------

  CREATE TABLE "STUDENT"."SKLEP" 
   (	"ID_SKLEPU" NUMBER, 
	"NAZWA_SKLEPU" VARCHAR2(32 BYTE), 
	"ADRES" VARCHAR2(32 BYTE), 
	"TELEFON_SKLEPU" VARCHAR2(32 BYTE), 
	"EMAIL_SKLEPU" VARCHAR2(32 BYTE), 
	"IMG_SKLEP" VARCHAR2(32 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
REM INSERTING into STUDENT.AUTO
SET DEFINE OFF;
Insert into STUDENT.AUTO (ID_AUTA,NAZWA,ROK,PRZEBIEG,POJEMNOSC,MOC,CENA,ID_DEALERA,ID_SKLEPU,IMG_AUTO,HIDDENN) values ('46','BMW M3','2003','150,000km','2.0L','200KM','20000','1','1','img/bmwm3.jpg','0');
Insert into STUDENT.AUTO (ID_AUTA,NAZWA,ROK,PRZEBIEG,POJEMNOSC,MOC,CENA,ID_DEALERA,ID_SKLEPU,IMG_AUTO,HIDDENN) values ('1','Renault Logan','2013','46000km','1.2L','75KM','12000','1','1','img/renaultlogan.jpg','0');
Insert into STUDENT.AUTO (ID_AUTA,NAZWA,ROK,PRZEBIEG,POJEMNOSC,MOC,CENA,ID_DEALERA,ID_SKLEPU,IMG_AUTO,HIDDENN) values ('47','Nissan Skyline','2010','100,000km','2.5L','300KM','17089','1','1','img/nissangtr.jpg','0');
Insert into STUDENT.AUTO (ID_AUTA,NAZWA,ROK,PRZEBIEG,POJEMNOSC,MOC,CENA,ID_DEALERA,ID_SKLEPU,IMG_AUTO,HIDDENN) values ('48','Ford KA+','2020','0km','1.2L','85KM','13000','1','1','img/fordka.jpg','0');
REM INSERTING into STUDENT.DEALER
SET DEFINE OFF;
Insert into STUDENT.DEALER (ID_DEALERA,NAZWA_DEALERA,KRAJ_POCHODZENIA,OPIS_DEALERA,IMG_DEALER) values ('1','Renault official','Francja','Renault - nie trzeba slow','img/renaultlogo.jpg');
REM INSERTING into STUDENT.HISTORY
SET DEFINE OFF;
REM INSERTING into STUDENT.KLIENT
SET DEFINE OFF;
Insert into STUDENT.KLIENT (ID_KLIENTA,IMIE,TELEFON_KLIENTA,EMAIL_KLIENTA,HASLO) values ('1','Admin','555 123 555','admin@email.com','admin');
Insert into STUDENT.KLIENT (ID_KLIENTA,IMIE,TELEFON_KLIENTA,EMAIL_KLIENTA,HASLO) values ('2','User','555 234 555','user@email.com','user123');
REM INSERTING into STUDENT.SKLEP
SET DEFINE OFF;
Insert into STUDENT.SKLEP (ID_SKLEPU,NAZWA_SKLEPU,ADRES,TELEFON_SKLEPU,EMAIL_SKLEPU,IMG_SKLEP) values ('1','Otomoto Cars','ul. Hetmanska 16','555123555','otomoto@email.com','img/otomoto.jpg');
--------------------------------------------------------
--  DDL for Index SKLEP_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."SKLEP_PK" ON "STUDENT"."SKLEP" ("ID_SKLEPU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index HISTORY_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."HISTORY_PK" ON "STUDENT"."HISTORY" ("ID_ZAKUPU") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK2
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."TABLE1_PK2" ON "STUDENT"."KLIENT" ("ID_KLIENTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK1
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."TABLE1_PK1" ON "STUDENT"."DEALER" ("ID_DEALERA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  DDL for Index TABLE1_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "STUDENT"."TABLE1_PK" ON "STUDENT"."AUTO" ("ID_AUTA") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K" ;
--------------------------------------------------------
--  Constraints for Table DEALER
--------------------------------------------------------

  ALTER TABLE "STUDENT"."DEALER" MODIFY ("ID_DEALERA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."DEALER" MODIFY ("NAZWA_DEALERA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."DEALER" MODIFY ("KRAJ_POCHODZENIA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."DEALER" MODIFY ("OPIS_DEALERA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."DEALER" ADD CONSTRAINT "TABLE1_PK1" PRIMARY KEY ("ID_DEALERA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SKLEP
--------------------------------------------------------

  ALTER TABLE "STUDENT"."SKLEP" MODIFY ("ID_SKLEPU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SKLEP" MODIFY ("NAZWA_SKLEPU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SKLEP" MODIFY ("ADRES" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SKLEP" MODIFY ("TELEFON_SKLEPU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SKLEP" MODIFY ("EMAIL_SKLEPU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SKLEP" MODIFY ("IMG_SKLEP" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."SKLEP" ADD CONSTRAINT "SKLEP_PK" PRIMARY KEY ("ID_SKLEPU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Constraints for Table AUTO
--------------------------------------------------------

  ALTER TABLE "STUDENT"."AUTO" MODIFY ("ID_AUTA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" ADD CONSTRAINT "TABLE1_PK" PRIMARY KEY ("ID_AUTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K"  ENABLE;
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("NAZWA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("ROK" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("PRZEBIEG" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("POJEMNOSC" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("MOC" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("CENA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("ID_DEALERA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("ID_SKLEPU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."AUTO" MODIFY ("HIDDENN" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table HISTORY
--------------------------------------------------------

  ALTER TABLE "STUDENT"."HISTORY" MODIFY ("ID_ZAKUPU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."HISTORY" ADD CONSTRAINT "HISTORY_PK" PRIMARY KEY ("ID_ZAKUPU")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "TMP_2K"  ENABLE;
  ALTER TABLE "STUDENT"."HISTORY" MODIFY ("ID_AUTA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."HISTORY" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."HISTORY" MODIFY ("DATA_ZAKUPU" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."HISTORY" MODIFY ("NAZWA_CAR" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table KLIENT
--------------------------------------------------------

  ALTER TABLE "STUDENT"."KLIENT" MODIFY ("ID_KLIENTA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENT" MODIFY ("IMIE" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENT" MODIFY ("TELEFON_KLIENTA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENT" MODIFY ("EMAIL_KLIENTA" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENT" MODIFY ("HASLO" NOT NULL ENABLE);
  ALTER TABLE "STUDENT"."KLIENT" ADD CONSTRAINT "TABLE1_PK2" PRIMARY KEY ("ID_KLIENTA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TMP_2K"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table AUTO
--------------------------------------------------------

  ALTER TABLE "STUDENT"."AUTO" ADD CONSTRAINT "AUTO_IBFK_1" FOREIGN KEY ("ID_DEALERA")
	  REFERENCES "STUDENT"."DEALER" ("ID_DEALERA") ON DELETE CASCADE ENABLE;
--------------------------------------------------------
--  DDL for Trigger AUTO_INC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STUDENT"."AUTO_INC" 
BEFORE INSERT ON auto
FOR EACH ROW 
BEGIN
SELECT id_seq.NEXTVAL
INTO :new.id_auta
FROM DUAL;
END;
/
ALTER TRIGGER "STUDENT"."AUTO_INC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger DEALER
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STUDENT"."DEALER" 
BEFORE INSERT ON dealer
FOR EACH ROW 
BEGIN
SELECT id_seq.NEXTVAL
INTO :new.id_dealera
FROM DUAL;
END;
/
ALTER TRIGGER "STUDENT"."DEALER" ENABLE;
--------------------------------------------------------
--  DDL for Trigger HISTORY_INC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STUDENT"."HISTORY_INC" 
BEFORE INSERT ON history
FOR EACH ROW 
BEGIN
SELECT id_seq.NEXTVAL
INTO :new.id_zakupu
FROM DUAL;
END;
/
ALTER TRIGGER "STUDENT"."HISTORY_INC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger KLIENT_INC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STUDENT"."KLIENT_INC" 
BEFORE INSERT ON klient
FOR EACH ROW 
BEGIN
SELECT id_seq.NEXTVAL
INTO :new.id_klienta
FROM DUAL;
END;
/
ALTER TRIGGER "STUDENT"."KLIENT_INC" ENABLE;
--------------------------------------------------------
--  DDL for Trigger SKLEP_INC
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "STUDENT"."SKLEP_INC" 
BEFORE INSERT ON sklep
FOR EACH ROW 
BEGIN
SELECT id_seq.NEXTVAL
INTO :new.id_sklepu
FROM DUAL;
END;
/
ALTER TRIGGER "STUDENT"."SKLEP_INC" ENABLE;
--------------------------------------------------------
--  DDL for Procedure ADMINADD
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "STUDENT"."ADMINADD" (
  nazwa1 in varchar2,
  rok1 in number,
  przebieg1 in varchar2,
  pojemnosc1 in varchar2,
  moc1 in varchar2,
  cena1 in number,
  id_dealera1 in number,
  id_sklepu1 in number,
  img_auto1 in varchar2
  )
    IS
  BEGIN
    INSERT INTO auto (nazwa, rok, przebieg, pojemnosc, moc, cena, id_dealera, id_sklepu, img_auto, hiddenn)
    VALUES (nazwa1, rok1, przebieg1, pojemnosc1, moc1, cena1, id_dealera1, id_sklepu1, img_auto1, 0);
  END adminadd;

/
--------------------------------------------------------
--  DDL for Procedure ADMINDELETE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "STUDENT"."ADMINDELETE" (
  id1 in number
  )
  IS
  BEGIN
    DELETE FROM auto WHERE id_auta=id1;
  END admindelete;

/
--------------------------------------------------------
--  DDL for Procedure ADMINUPDATE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "STUDENT"."ADMINUPDATE" (
  cena1 in number,
  id1 in number
  )
  IS
  BEGIN
    UPDATE auto SET cena = cena1 WHERE id_auta = id1;
  END adminupdate;

/
